services:
  _dummy:
    image: alpine
    command: ["true"]

networks:
  businesscasehb:
    name: business-case-network
    driver: bridge

include:
  - backend/docker-compose.yml
  - frontend/docker-compose.yml
