services:
    mysql:
        image: mysql:8.3
        container_name: business-case-db
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "user",
                    "-ppassword",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - business-case-network

    mysql-test:
        image: mysql:8.3
        container_name: business-case-test-db
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "user",
                    "-ppassword",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-test_data:/var/lib/mysql
        networks:
            - business-case-network

    app:
        build: ./
        container_name: business-case-back
        depends_on:
            mysql:
                condition: service_healthy
            mysql-test:
                condition: service_healthy
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: ${MYSQL_DATABASE}
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
        env_file:
            - .env
        command: ["tail", "-f", "/dev/null"]
        networks:
                - business-case-network

volumes:
    mysql_data:
    mysql-test_data:

networks:
    business-case-network:
