# Nested docker-compose
# db:
#     extends:
#         file: api/docker-compose.yml
# #         service: "mysql"
services:
    mysql:
        image: mysql:8.3
        container_name: business-case-db
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "user",
                    "-ppassword",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mysql-test:
        image: mysql:8.3
        container_name: business-case-test-db
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "user",
                    "-ppassword",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - mysql-test_data:/var/lib/mysql

    app:
        build: ./
        container_name: business-case-back
        depends_on:
            mysql:
                condition: service_healthy # Wait for db to be healthy
            mysql-test:
                condition: service_healthy # Wait for the test db to be healthy
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
            interval: 10s
            timeout: 5s
            retries: 10
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: ${MYSQL_DATABASE}
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            VIRTUAL_HOST: "" # Nginx ignores this container and prevents load balancing
        env_file:
            - .env
        ports:
            - "8080:8080"
        command: ["tail", "-f", "/dev/null"] # == While True to keep the process alive with minimal resources consumption
        networks:
            - business-case-network

networks:
    business-case-network:

volumes:
    mysql_data:
    mysql-test_data:
